language: ruby
bundler_args: --without development
script: 'bundle exec rake test'
services:
  - mongodb
rvm:
  # - 1.8.7
  # - 1.9.3
  - 2.0.0
env:
  - DB=mongodb
  - DB=redis
  - DB=mysql
  #- DB=postgres
gemfile:
  - Gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
before_script:
  - "mysql -e 'create database vanity_test;' >/dev/null"
  #- "psql -c 'create database vanity_test;' -U postgres >/dev/null"
matrix:
  allow_failures:
  exclude:
    - rvm: 2.0.0
      env: DB=mongodb
      gemfile: Gemfile
    - rvm: 2.0.0
      env: DB=redis
      gemfile: Gemfile
    - rvm: 2.0.0
      env: DB=mysql
      gemfile: Gemfile
